# What protocol to use when performing git operations. Supported values: ssh, https
git_protocol: https
# What editor gh should run when creating issues, pull requests, etc. If blank, will refer to environment.
editor:
# Aliases allow you to create nicknames for gh commands
aliases:
    co: pr checkout
    new: repo create --private --source . --push
    new-: repo create --public --source . --push
    reporm: api -X DELETE "repos/$1"
    repomv: api -X PATCH "repos/$1" -f name="$2" --jq ".html_url"
    repotf: api -X POST "repos/$1/transfer" -f new_owner="$2" --jq ".html_url"
    repoar: api -X PATCH "repos/$1" -f archived=true --jq ".archived"
