#!/usr/bin/env bash

abort()   { printf '\e[1m\e[38;5;9m✗\e[0m   \e[1m%s\e[0m\n'  "$*" >&2; exit 1;     }
warn()    { printf '\e[1m\e[38;5;11m!\e[0m   \e[1m%s\e[0m\n' "$*" >&2;             }

check() {
	if ! command -v cog &>/dev/null; then
		warn 'Cog required to check commit'
		return 0
	fi

	if cog check; then
	    return 0
	fi

	abort "Invalid commits were found, force push with '--no-verify'"
}

main() {
	if [[ $(git config hooks.conventional-commits 2>/dev/null || true) != true ]]; then
		exit 0
	fi
	if [[ $(git config hooks.pre-push 2>/dev/null || true) == false ]]; then
		exit 0
	fi
	if [[ $(git for-each-ref --format='%(refname)' refs/heads/ | wc -l) -le 1 ]]; then
		exit 0
	fi

	check
}

main "$@"
